groups:
  - name: postgresql.rules
    rules:
      # Connection Limits
      - alert: PostgreSQLConnectionsHigh
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 2m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL connections are running high"
          description: "PostgreSQL connections are {{ $value }}% of the maximum allowed connections on {{ $labels.instance }}"

      - alert: PostgreSQLConnectionsCritical
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 95
        for: 1m
        labels:
          severity: critical
          service: postgresql
        annotations:
          summary: "PostgreSQL connections are critically high"
          description: "PostgreSQL connections are {{ $value }}% of the maximum allowed connections on {{ $labels.instance }}"

      # Database Performance
      - alert: PostgreSQLSlowQueries
        expr: rate(pg_stat_activity_max_tx_duration[5m]) > 60
        for: 2m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL slow queries detected"
          description: "PostgreSQL has slow queries running for more than 60 seconds on {{ $labels.instance }}"

      - alert: PostgreSQLDeadlocks
        expr: rate(pg_stat_database_deadlocks[5m]) > 0
        for: 1m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL deadlocks detected"
          description: "PostgreSQL has {{ $value }} deadlocks per second on {{ $labels.instance }}"

      # System Resources
      - alert: PostgreSQLDiskUsageHigh
        expr: (pg_database_size_bytes / pg_tablespace_size_bytes) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL disk usage is high"
          description: "PostgreSQL disk usage is {{ $value }}% on {{ $labels.instance }}"

      # Replication
      - alert: PostgreSQLReplicationLag
        expr: pg_stat_replication_lag_seconds > 30
        for: 1m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL replication lag is high"
          description: "PostgreSQL replication lag is {{ $value }} seconds on {{ $labels.instance }}"

      # Service Availability
      - alert: PostgreSQLDown
        expr: pg_up != 1
        for: 1m
        labels:
          severity: critical
          service: postgresql
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL instance {{ $labels.instance }} is down"
