global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'postgresql-monitoring'
    replica: 'prometheus-1'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    honor_labels: true
    params:
      collect[]:
        - 'pg_stat_database'
        - 'pg_stat_user_tables'
        - 'pg_stat_activity'
        - 'pg_locks'
        - 'pg_stat_replication'

  # Multi-host PostgreSQL instances (add additional hosts here)
  - job_name: 'postgres-exporter-host2'
    static_configs:
      - targets: ['host2.example.com:9187']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    honor_labels: true

  # Node Exporter for system metrics (optional)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
