apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
    secureJsonData:
      httpHeaderValue1: 'Bearer your-token-here'
  
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: postgres
    user: grafana
    secureJsonData:
      password: grafana_db_password_here
    jsonData:
      sslmode: require
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1700
      timescaledb: false
