apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
    - name: PostgreSQL
    type: postgres
    access: proxy
    url: YOUR_WINDOWS_SERVER_IP:5432  # Replace with your server IP
    database: postgres
    user: postgres_exporter  # Or create a separate read-only user
    secureJsonData:
      password: your_secure_exporter_password
    jsonData:
      sslmode: prefer  # Use 'disable' if SSL not configured
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1700
      timescaledb: false
